// Command genmanifest regenerates pkg/assets/manifest_gen.go from the
// files in public/static/img.
//
// Run it after adding, removing or regenerating imagery:
//
//	go run ./pkg/assets/cmd/genmanifest
package main

import (
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	staticRoot = "public/static"
	outPath    = "pkg/assets/manifest_gen.go"
)

func main() {
	imgRoot := filepath.Join(staticRoot, "img")

	var photos, variants, flags []string
	err := filepath.WalkDir(imgRoot, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		rel, relErr := filepath.Rel(staticRoot, p)
		if relErr != nil {
			return nil
		}
		url := "/static/" + filepath.ToSlash(rel)

		switch {
		case strings.HasSuffix(url, ".webp"):
			variants = append(variants, url)
		case strings.HasSuffix(url, ".jpg") && strings.Contains(url, "/img/properties/"):
			photos = append(photos, url)
		case strings.HasSuffix(url, ".svg") && strings.Contains(url, "/img/flags/"):
			// The filename is the lowercase ISO 3166-1 alpha-2 code.
			code := strings.TrimSuffix(filepath.Base(url), ".svg")
			flags = append(flags, strings.ToUpper(code))
		}
		return nil
	})
	if err != nil {
		log.Fatalf("walk %s: %v", imgRoot, err)
	}

	sort.Strings(photos)
	sort.Strings(variants)
	sort.Strings(flags)

	var b strings.Builder
	b.WriteString("// Code generated by pkg/assets/cmd/genmanifest. DO NOT EDIT.\n\n")
	b.WriteString("package assets\n\n")

	b.WriteString("// propertyPhotos lists the property photographs, filename-ordered so the\n")
	b.WriteString("// mock data layer assigns galleries deterministically.\n")
	b.WriteString("var propertyPhotos = []string{\n")
	for _, p := range photos {
		fmt.Fprintf(&b, "\t%q,\n", p)
	}
	b.WriteString("}\n\n")

	b.WriteString("// imageVariants lists every generated responsive WebP file.\n")
	b.WriteString("var imageVariants = []string{\n")
	for _, v := range variants {
		fmt.Fprintf(&b, "\t%q,\n", v)
	}
	b.WriteString("}\n\n")

	b.WriteString("// flagCodes lists the ISO 3166-1 alpha-2 codes that have a local SVG\n")
	b.WriteString("// flag in public/static/img/flags. The template helper checks this before\n")
	b.WriteString("// emitting an <img>, so an unknown code renders a neutral placeholder\n")
	b.WriteString("// rather than a broken image.\n")
	b.WriteString("var flagCodes = []string{\n")
	for _, f := range flags {
		fmt.Fprintf(&b, "\t%q,\n", f)
	}
	b.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("write %s: %v", outPath, err)
	}
	fmt.Printf("wrote %s: %d photos, %d variants, %d flags\n",
		outPath, len(photos), len(variants), len(flags))
}
