// Command genmanifest regenerates internal/assets/manifest_gen.go from the
// files in public/static/img.
//
// Run it after adding, removing or regenerating imagery:
//
//	go run ./internal/assets/cmd/genmanifest
package main

import (
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const (
	staticRoot = "public/static"
	outPath    = "internal/assets/manifest_gen.go"
)

func main() {
	imgRoot := filepath.Join(staticRoot, "img")

	var photos, variants []string
	err := filepath.WalkDir(imgRoot, func(p string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return err
		}
		rel, relErr := filepath.Rel(staticRoot, p)
		if relErr != nil {
			return nil
		}
		url := "/static/" + filepath.ToSlash(rel)

		switch {
		case strings.HasSuffix(url, ".webp"):
			variants = append(variants, url)
		case strings.HasSuffix(url, ".jpg") && strings.Contains(url, "/img/properties/"):
			photos = append(photos, url)
		}
		return nil
	})
	if err != nil {
		log.Fatalf("walk %s: %v", imgRoot, err)
	}

	sort.Strings(photos)
	sort.Strings(variants)

	var b strings.Builder
	b.WriteString("// Code generated by internal/assets/cmd/genmanifest. DO NOT EDIT.\n\n")
	b.WriteString("package assets\n\n")

	b.WriteString("// propertyPhotos lists the property photographs, filename-ordered so the\n")
	b.WriteString("// mock data layer assigns galleries deterministically.\n")
	b.WriteString("var propertyPhotos = []string{\n")
	for _, p := range photos {
		fmt.Fprintf(&b, "\t%q,\n", p)
	}
	b.WriteString("}\n\n")

	b.WriteString("// imageVariants lists every generated responsive WebP file.\n")
	b.WriteString("var imageVariants = []string{\n")
	for _, v := range variants {
		fmt.Fprintf(&b, "\t%q,\n", v)
	}
	b.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(b.String()), 0o644); err != nil {
		log.Fatalf("write %s: %v", outPath, err)
	}
	fmt.Printf("wrote %s: %d photos, %d variants\n", outPath, len(photos), len(variants))
}
